In [518]:


import pandas as pd
import numpy as np
import os

#---------ANALYSIS OF DIFFICULTY----------

df = pd.read_csv('Comparison2.csv')
#read Session 2 Comparison Questionnaire CSV file, raw data


#to read column headers use print(comparison2.columns)

df.describe()
#Statistical summary of User-study Session 2 responses from participants after using the software

,Difficulty_Wizard,Difficulty_QuickForm,Difficulty_WebProtege,Difficulty_WikiData,RankDiff,ExpDiff,Helpfulness_Wizard,Helpfulness_QuickForm,Helpfulness_WebProtege,Helpfulness_Wiki,RankHelpfulness,ExpHelpfulness,Confdence_Wizard,Confidence_QuickForm,Confidence_WebProtege,Confidence_WikiData
count,28.000000,28.000000,28.000000,28.000000,28.000000,0.0,28.000000,28.000000,28.000000,28.000000,28.000000,0.0,28.000000,28.000000,28.000000,28.000000
mean,2.142857,1.178571,2.928571,3.750000,1.464286,NaN,2.142857,2.642857,2.642857,2.571429,1.785714,NaN,3.714286,4.392857,3.107143,2.321429
std,0.705234,0.390021,0.662687,0.585314,0.507875,NaN,1.044005,1.311326,0.951190,1.136224,0.568112,NaN,1.013141,0.628890,1.030616,0.818923
min,1.000000,1.000000,1.000000,2.000000,1.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,2.000000,3.000000,1.000000,1.000000
25%,2.000000,1.000000,3.000000,4.000000,1.000000,NaN,1.000000,1.000000,2.000000,2.000000,1.000000,NaN,3.000000,4.000000,3.000000,2.000000
50%,2.000000,1.000000,3.000000,4.000000,1.000000,NaN,2.000000,2.500000,3.000000,2.500000,2.000000,NaN,4.000000,4.000000,3.000000,2.000000
75%,2.250000,1.000000,3.000000,4.000000,2.000000,NaN,3.000000,4.000000,3.000000,4.000000,2.000000,NaN,4.250000,5.000000,4.000000,3.000000
max,4.000000,2.000000,4.000000,4.000000,2.000000,NaN,4.000000,4.000000,4.000000,4.000000,3.000000,NaN,5.000000,5.000000,5.000000,4.000000

In [657]:
#Difficulty - breakdown of ranking for difficulty given by study participants after using the interface. 
#Columns broken down for Wizard, QuickFrom, WikiData, and WebProtege
difficulty =df[['Difficulty_Wizard','Difficulty_QuickForm','Difficulty_WikiData','Difficulty_WebProtege']]

difficulty_long=pd.melt(difficulty, var_name='Tool', value_name='Rating')
variable_split=difficulty_long['Tool'].str.split('_')
variable_split=variable_split.str[1]                              
difficulty_long['Tool']=variable_split
difficulty=difficulty_long[['Tool','Rating']]

#difficulty

In [671]:
#Frequency Table
difficulty_table=pd.crosstab(difficulty_long.Rating, difficulty_long.Tool)
difficulty_table

Tool    QuickForm  WebProtege  WikiData  Wizard
Rating
1              23           1         0       4
2               5           4         2      17
3               0          19         3       6
4               0           4        23       1

In [676]:
#Pivot Table
difficulty_pivot=difficulty_long.pivot_table(values='Rating', columns='Tool').round(0).astype(int).mode()
columnOrder=['QuickForm', 'Wizard', 'WebProt', 'Wiki']
difficulty_pivot.reindex(columns=columnOrder)
difficulty_pivot.style.hide_index()

In [664]:
#Total responses for difficulty
pd.value_counts(difficulty['Tool'])

QuickForm     28
WikiData      28
Wizard        28
WebProtege    28
Name: Tool, dtype: int64

In [677]:
#Ranked total - participants given a scale of 1-4 with 1 being easier to use & 4 harder to use.
#Scale - lower total (easier) - higher total (harder)
difficulty2 = difficulty.groupby(['Tool'], as_index=False).sum()
difficulty2.sort_values(by='Rating')

         Tool  Rating
0   QuickForm      33
3      Wizard      60
1  WebProtege      82
2    WikiData     105

In [680]:
#Summary of what respondents selected when ranking difficultyfor Wizard
#17 people ranked it as 2 withing the 1-4 difficulty scale
df.groupby('Difficulty_Wizard').size()

Difficulty_Wizard
1     4
2    17
3     6
4     1
dtype: int64

In [681]:
#Summary of what respondents selected when ranking difficulty for WikiData
#23 people ranked it as 4 withing the 1-4 difficulty scale (hardest)
df.groupby('Difficulty_WikiData').size())

Difficulty_WikiData
2     2
3     3
4    23
dtype: int64

In [682]:
#Summary of what respondents selected when ranking difficulty for WikiData
#19 people ranked it as 3 within the 1-4 difficulty scale (hardest)
df.groupby('Difficulty_WebProtege').size()

Difficulty_WebProtege
1     1
2     4
3    19
4     4
dtype: int64